### ISSUE TITLE
No room at data center for allocating the server

### ISSUE THREAD

**Issue by crbertoldo** [nfvlabs/openmano#11]
I could not get the concept of 'room' when trying to debug the output below following the Getting Started with 'test' mode.

root@ubuntu1410server:/home/adminuser/openmano/openmano# ./openmano scenario-deploy complex complex-instance
Error creating vm instance: Error in VIM "http://localhost:9080/openvim": not possible to add new vm instance. HTTP Response: 400. Error: No room at data center for allocating the server. Rollback successful

I've also tried after deleting the 'simple' scenario (./openmano instance-scenario-delete) thinking in any resource release, but unsuccessful.

Please, any suggestion?

**Comment by gerardo-garcia** [comment]
Even in test mode, you should have 'fake' hosts in order to deploy VNFs.
You can use the examples suggested in the Getting Started guide:
  ./openvim host-add test/hosts/host-example0.json
  ./openvim host-add test/hosts/host-example1.json
  ./openvim host-add test/hosts/host-example2.json
  ./openvim host-add test/hosts/host-example3.json

In summary, in test mode you won't deploy the VMs in the hosts, but the resource orchestration is still done. Therefore, enough room is needed to allocate all the VMs of a network scenario.

**Comment by crbertoldo** [comment]
That is the point. The fake hosts were there. I could even see them in WebUI (besides of thru list in CLI). The guide was follewed.

**Comment by gerardo-garcia** [comment]
Please send us by e-mail to nfvlabs@tid.es the file report,txt, after executing the following commands:
    git pull                                                          # to update to the latest version of the code
    ./scripts/openmano-report.sh > report.txt    # to generate a report

**Comment by alf-tierno** [comment]
The problem, happens because the file "openvim/database_utils/of_ports_pci_correspondence.sql" does not contain an entry for each ethernet port of the added hosts. This causes that even there are ethernet ports, none of them are available because none of them are connected to the openflow switch. The result is that "complex" VNF that contain dataplane can not be physically deployed. Openvim cannot find a host with "openflow connected" ethernet ports and return the error "no room" for allocating this virtual machine

Current commit on 2015-05-05 solves this problem. Load "of_ports_pci_correspondence.sql" at database and afterwards the hosts. For example follown the steps:
$openvim/database_utils/init_vim_db.sh
$openvim openvim host-add test/hosts/host-example0.json    ...
