### ISSUE TITLE
VMs are still running after deleting an instance scenario

### ISSUE THREAD

**Issue by alogracia** [nfvlabs/openmano#21]
This is happening with VMs that do not respond to shutdown signal sent by openvim. A destroy signal from openvim is required in case shutdown is failing after a time out.

**Comment by gerardo-garcia** [comment]
The destroy signal is not sent because openvim cannot find the domain id through libvirt.

This is the output in openvim log:
libvirt: QEMU Driver error : Domain not found: no domain with matching uuid '2c553b74-26d5-11e5-a988-525400f9969d'
test01 : action_on_server( 2c553b74-26d5-11e5-a988-525400f9969d ) domain not running

**Comment by alogracia** [comment]
Fixed after upgrading openmano installation. Thanks.
