### ISSUE TITLE
Where I can download yams files which are for the developer mode practices?

### ISSUE THREAD

**Issue by pengminjiong** [nfvlabs/openmano#26]
I finished test mode but failed in developer part.
I cannot find yamls files(description files )that mentioned in your presentation,  http://movilforum.com/presentaciones-nfv/ 

for example: yamls/scenario.yamls
                     yamlsgateway.yamls

I am a student so forgive to ask such a simple question.

**Comment by pengminjiong** [comment]
Also Error: Error copying image to localhost:cp:cannot stat "/path/to/imagefolder/linux.qcow2": no such file or directory.

**Comment by alf-tierno** [comment]
Sorry for the delate,
Find attached the needed yamls, for some reason it has not been published.

Note that you need to edit developer_host.yaml with your “user” and “ip_name”

Regards
---
Alfonso

De: pengminjiong [mailto:notifications@github.com]
Enviado el: sábado, 10 de octubre de 2015 10:27
Para: nfvlabs/openmano
Asunto: [openmano] Where I can download yams files which are for the developer mode practices? (#26)


I finished test mode but failed in developer part.
I cannot find yamls files(description files )that mentioned in your presentation, http://movilforum.com/presentaciones-nfv/

for example: yamls/scenario.yamls
yamlsgateway.yamls

I am a student so forgive to ask such a simple question.

—
Reply to this email directly or view it on GitHub<https://github.com/nfvlabs/openmano/issues/26>.

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição

**Comment by alf-tierno** [comment]
Yes, this is because in the field “VNFC: VNFC image:” of your VNF descriptor, you need to provide a path to a real image file that must be “read only” reachable from the compute hosts. This field remains untouched, so that openvim makes a copy into the working directory before deploying the virtual machine.
In our examples we put this “"/path/to/imagefolder/linux.qcow2” that works for “test” mode, but you need to put a real one for the other modes.

---
Alfonso

De: pengminjiong [mailto:notifications@github.com]
Enviado el: lunes, 12 de octubre de 2015 8:48
Para: nfvlabs/openmano
Asunto: Re: [openmano] Where I can download yams files which are for the developer mode practices? (#26)


Also Error: Error copying image to localhost:cp:cannot stat "/path/to/imagefolder/linux.qcow2": no such file or directory.

—
Reply to this email directly or view it on GitHub<https://github.com/nfvlabs/openmano/issues/26#issuecomment-147301832>.

________________________________

Este mensaje y sus adjuntos se dirigen exclusivamente a su destinatario, puede contener información privilegiada o confidencial y es para uso exclusivo de la persona o entidad de destino. Si no es usted. el destinatario indicado, queda notificado de que la lectura, utilización, divulgación y/o copia sin autorización puede estar prohibida en virtud de la legislación vigente. Si ha recibido este mensaje por error, le rogamos que nos lo comunique inmediatamente por esta misma vía y proceda a su destrucción.

The information contained in this transmission is privileged and confidential information intended only for the use of the individual or entity named above. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this transmission in error, do not read it. Please immediately reply to the sender that you have received this communication in error and then delete it.

Esta mensagem e seus anexos se dirigem exclusivamente ao seu destinatário, pode conter informação privilegiada ou confidencial e é para uso exclusivo da pessoa ou entidade de destino. Se não é vossa senhoria o destinatário indicado, fica notificado de que a leitura, utilização, divulgação e/ou cópia sem autorização pode estar proibida em virtude da legislação vigente. Se recebeu esta mensagem por erro, rogamos-lhe que nos o comunique imediatamente por esta mesma via e proceda a sua destruição

**Comment by alf-tierno** [comment]
You can download the yaml descriptors of the mentioned Movilforum training from:
https://github.com/alf-tierno/openmano-descriptors/tree/master/movilforum2015

**Comment by pengminjiong** [comment]
Thank you so much alf-tierno , I followed your presentation ,  and I wonder if you can also provide the images of VNFs. Because without those images, we cannot finished the development practice. 

Best regards
